spring.application.name=serviceplatform
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
spring.datasource.username=${DB_USERNAME:postgres.eyfodxzoorkakzfagpes}
spring.datasource.password=${DB_PASSWORD:Sabyasachi@21}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwt.secret=${JWT_SECRET:9Z0zX2H0QjO2bE1QfT7sY0gO1zT8R5eI9Z0zX2H0QjO2bE1QfT7sY0gO1zT8R5eI}
app.jwt.expiration-ms=86400000

# Mail Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=mock_username
spring.mail.password=mock_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server port
server.port=${PORT:8082}
